FROM docker.io/verizonmedia/yavin:web_latest

RUN apt-get install -y netcat

WORKDIR /usr/src/yavin
CMD . scripts/jdbc_url.sh && env && nc -l -p ${PORT} -w50 -v && java -Xmx224m -Dspring.profiles.active=heroku_postgress -jar /usr/src/yavin/packages/webservice/app/build/libs/app-0.2.0.jar
