FROM openjdk:11

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs

ENV PORT=8080
COPY . /usr/src/yavin

ENV DISABLE_MOCKS=true
WORKDIR /usr/src/yavin
RUN  npm ci -verbose
RUN  node_modules/.bin/lerna bootstrap --ci --concurrency=2 --loglevel warn
RUN  node_modules/.bin/lerna run build --scope navi-app --stream

WORKDIR /usr/src/yavin/packages/webservice
RUN ./gradlew bootJar
RUN cp -r ./../app/dist app/build/resources/main/META-INF/resources/ui

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

WORKDIR /usr/src/yavin
#CMD . scripts/jdbc_url.sh && env && java -Xmx224m -Dspring.profiles.active=heroku -jar /usr/src/yavin/packages/webservice/app/build/libs/app-0.2.0.jar
CMD . scripts/jdbc_url.sh && env && java -Xmx224m -Dspring.profiles.active=heroku_postgress -jar /usr/src/yavin/packages/webservice/app/build/libs/app-0.2.0.jar
